name: pigu

on:
  push:
    tags:
      - "*"
  schedule:
    - cron: "30 2-9 * * 1-5"

jobs:
  TakeCareYourAss:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm
          utcOffset: "+08:00"
      - name: Send dingding notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          body: |
            {
              "msgtype": "actionCard", 
              "actionCard": {
                "title":"温馨提示",
                "text": "![image.png](https://cdn.gelonghui.com/ad/0cf7b-04586857-b09f-4095-bd40-3cef609c591f.png)\n
                现在时间： ${{ steps.current-time.outputs.formattedTime }} \n
                打工人！身体是打工的本钱～ \n
                from wlb-bot \n
                "
              },
              "at": {
                  "atMobiles": [],
                  "isAtAll": true
                }
            }
